user_dir: "/home/jenkins"
app_port: 5000
app_user: jenkins
service:
  workingdir: "{{user_dir}}/adminSystem/base"
  execstart: "{{user_dir}}/adminSystem/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind  base.wsgi:application"

djangoservice:
  workingdir: "{{user_dir}}/adminSystem/base"
  execstart: "{{user_dir}}/adminSystem/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind  base.wsgi:application"



app:
  env:
    SQLALCHEMY_DATABASE_URI: postgres://myprojectuser:password@localhost:/myproject
    SQLALCHEMY_TRACK_MODIFICATIONS: False
    SECRET_KEY: test123

django:
  env:
    SECRET_KEY: test123
    DATABASE_URL: postgres://myprojectuser:password@localhost:/myproject

