user_dir: "/home/vagrant"
app_port: 5000
service:
  workingdir: /home/vagrant/adminSystem/base
  execstart: /home/vagrant/adminSystem/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8001 base.wsgi:application

djangoservice:
  workingdir: /home/vagrant/adminSystem/base
  execstart: /home/vagrant/adminSystem/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8001 base.wsgi:application



app:
  env:
    SQLALCHEMY_DATABASE_URI: postgres://myprojectuser:password@localhost:/myproject
    SQLALCHEMY_TRACK_MODIFICATIONS: False
    SECRET_KEY: test123

django:
  env:
    SECRET_KEY: test123
    DATABASE_URL: postgres://myprojectuser:password@localhost:/myproject
